from pydantic import BaseModel
from typing import Optional, List


class InvestmentMemo(BaseModel):
    ticker: str
    company_name: str
    executive_summary: str
    business_overview: str
    financial_highlights: str
    valuation_analysis: str
    risk_factors: str
    recommendation: str


class AdvisoryReport(BaseModel):
    ticker: str
    funding_options: List[str]
    strategic_options: List[str]
    market_positioning: str
    recommendation: str
    disclaimer: str = (
        "This analysis was generated by CorpFinAI for educational purposes only. "
        "It does not constitute investment advice."
    )
