"""
PDF Investment Memo Generator using ReportLab.
Produces a professional 4-5 page investment memo with:
- Cover page, executive summary, financial highlights,
  valuation analysis, strategic advisory, disclaimer.
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
import logging
import os
import tempfile

logger = logging.getLogger(__name__)

DARK_BLUE = HexColor("#1B3A5C")
MEDIUM_BLUE = HexColor("#2C5F8A")
LIGHT_GRAY = HexColor("#F5F5F5")
WHITE = HexColor("#FFFFFF")


def _get_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(
        name="CoverTitle", fontSize=28, textColor=DARK_BLUE,
        alignment=TA_CENTER, spaceAfter=12, fontName="Helvetica-Bold",
    ))
    styles.add(ParagraphStyle(
        name="CoverSubtitle", fontSize=14, textColor=HexColor("#666666"),
        alignment=TA_CENTER, spaceAfter=6,
    ))
    styles.add(ParagraphStyle(
        name="SectionTitle", fontSize=16, textColor=DARK_BLUE,
        fontName="Helvetica-Bold", spaceBefore=20, spaceAfter=10,
    ))
    styles.add(ParagraphStyle(
        name="BodyText2", fontSize=10, textColor=HexColor("#333333"),
        alignment=TA_JUSTIFY, spaceAfter=8, leading=14,
    ))
    styles.add(ParagraphStyle(
        name="Disclaimer", fontSize=8, textColor=HexColor("#999999"),
        alignment=TA_CENTER, spaceAfter=4, leading=10,
    ))
    return styles


class PDFMemoGenerator:
    def generate(
        self,
        ticker: str,
        company: dict,
        ratios: dict,
        scenarios: list,
        advisory: str,
        agent_analysis: str,
        monte_carlo: dict = None,
        quality_checks: list = None,
        output_path: str = None,
    ) -> str:
        if not output_path:
            output_path = os.path.join(tempfile.gettempdir(), f"{ticker}_memo.pdf")

        doc = SimpleDocTemplate(
            output_path, pagesize=A4,
            leftMargin=25 * mm, rightMargin=25 * mm,
            topMargin=20 * mm, bottomMargin=20 * mm,
        )
        styles = _get_styles()
        story = []

        # ---- Cover Page ----
        story.append(Spacer(1, 2 * inch))
        story.append(Paragraph(
            f"{company.get('name', ticker)} ({ticker})", styles["CoverTitle"]
        ))
        story.append(Paragraph("Investment Memo", styles["CoverSubtitle"]))
        story.append(Paragraph("Corporate Finance Analysis", styles["CoverSubtitle"]))
        story.append(Spacer(1, 0.5 * inch))
        story.append(HRFlowable(width="60%", color=MEDIUM_BLUE, thickness=2))
        story.append(Spacer(1, 0.3 * inch))

        mc = company.get("market_cap")
        mc_str = f"${mc / 1e9:.1f}B" if mc and mc > 0 else "N/A"
        cover_info = [
            f"Sector: {company.get('sector', 'N/A')} | Industry: {company.get('industry', 'N/A')}",
            f"Market Cap: {mc_str} | Country: {company.get('country', 'N/A')}",
            "Generated by CorpFinAI | For Educational Purposes Only",
        ]
        for line in cover_info:
            story.append(Paragraph(line, styles["CoverSubtitle"]))

        story.append(PageBreak())

        # ---- Executive Summary ----
        story.append(Paragraph("Executive Summary", styles["SectionTitle"]))
        desc = company.get("description", "No description available.")
        story.append(Paragraph(desc[:800], styles["BodyText2"]))
        story.append(Spacer(1, 0.2 * inch))

        # ---- Financial Highlights ----
        story.append(Paragraph("Financial Highlights", styles["SectionTitle"]))

        sorted_periods = sorted(ratios.keys())[-4:]
        if sorted_periods:
            header = ["Metric"] + sorted_periods
            rows = [header]

            metrics = [
                ("Revenue ($M)", "revenue", 1e6),
                ("EBITDA ($M)", "ebitda", 1e6),
                ("Net Income ($M)", "net_income", 1e6),
                ("Gross Margin", "gross_margin", None),
                ("EBITDA Margin", "ebitda_margin", None),
                ("Revenue Growth", "revenue_growth", None),
                ("Debt/Equity", "debt_to_equity", None),
            ]

            for label, key, divisor in metrics:
                row = [label]
                for period in sorted_periods:
                    val = ratios.get(period, {}).get(key)
                    if val is None:
                        row.append("N/A")
                    elif divisor:
                        row.append(f"{val / divisor:,.0f}")
                    else:
                        row.append(f"{val:.1%}")
                rows.append(row)

            table = Table(rows, repeatRows=1)
            table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), DARK_BLUE),
                ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#CCCCCC")),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
                ("ALIGN", (1, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(table)
            story.append(Spacer(1, 0.3 * inch))

        # ---- Scenario Analysis ----
        story.append(Paragraph("Scenario Analysis", styles["SectionTitle"]))

        if scenarios:
            s_header = ["Metric"]
            for s in scenarios:
                a = s.get("assumptions", {}) if isinstance(s, dict) else {}
                s_header.append(a.get("label", "Scenario"))

            s_rows = [s_header]
            s_metrics = [
                ("Revenue Growth", lambda s: f"{s.get('assumptions',{}).get('revenue_growth_rate',0):.1%}"),
                ("EBITDA Margin", lambda s: f"{s.get('assumptions',{}).get('ebitda_margin',0):.1%}"),
                ("WACC", lambda s: f"{s.get('assumptions',{}).get('wacc',0):.1%}"),
                ("DCF Value", lambda s: f"${s.get('dcf_value',0)/1e9:.1f}B"),
                ("Implied Price", lambda s: f"${s.get('implied_share_price',0):,.2f}"),
            ]

            for label, fn in s_metrics:
                row = [label]
                for s in scenarios:
                    row.append(fn(s) if isinstance(s, dict) else "N/A")
                s_rows.append(row)

            s_table = Table(s_rows, repeatRows=1)
            s_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), MEDIUM_BLUE),
                ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#CCCCCC")),
                ("ALIGN", (1, 0), (-1, -1), "CENTER"),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]))
            story.append(s_table)
            story.append(Spacer(1, 0.3 * inch))

        # ---- Monte Carlo Summary ----
        if monte_carlo and not monte_carlo.get("error"):
            story.append(Paragraph("Monte Carlo Simulation", styles["SectionTitle"]))
            mc_text = (
                f"Based on {monte_carlo.get('n_simulations', 0):,} simulations with randomized "
                f"assumptions, the implied share price has a median of "
                f"${monte_carlo.get('median_price', 0):,.2f} with a 90% confidence interval "
                f"of ${monte_carlo.get('percentile_5', 0):,.2f} to "
                f"${monte_carlo.get('percentile_95', 0):,.2f}. "
                f"Standard deviation is ${monte_carlo.get('std_dev', 0):,.2f}."
            )
            story.append(Paragraph(mc_text, styles["BodyText2"]))
            story.append(Spacer(1, 0.2 * inch))

        story.append(PageBreak())

        # ---- Strategic Advisory ----
        story.append(Paragraph("Strategic Advisory", styles["SectionTitle"]))
        advisory_text = advisory or agent_analysis or "Advisory not available."
        # Split long text into paragraphs
        for para in advisory_text.split("\n"):
            if para.strip():
                story.append(Paragraph(para.strip()[:500], styles["BodyText2"]))

        story.append(Spacer(1, 0.3 * inch))

        # ---- Quality Checks Summary ----
        if quality_checks:
            story.append(Paragraph("Quality Evaluation", styles["SectionTitle"]))
            passed = sum(1 for c in quality_checks if c.get("passed"))
            total = len(quality_checks)
            story.append(Paragraph(
                f"{passed} of {total} automated quality checks passed.",
                styles["BodyText2"],
            ))
            story.append(Spacer(1, 0.3 * inch))

        # ---- Disclaimer ----
        story.append(HRFlowable(width="100%", color=HexColor("#CCCCCC"), thickness=1))
        story.append(Spacer(1, 0.2 * inch))
        story.append(Paragraph(
            "DISCLAIMER: This analysis was generated by CorpFinAI for educational purposes only. "
            "It does not constitute investment advice. All projections are estimates "
            "based on publicly available data and stated assumptions. "
            "Actual results may differ materially.",
            styles["Disclaimer"],
        ))

        # Build PDF
        doc.build(story)
        logger.info(f"PDF memo generated: {output_path}")
        return output_path
