from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import logging
import tempfile
import os

logger = logging.getLogger(__name__)

# Color palette
DARK_BLUE = RGBColor(0x1B, 0x3A, 0x5C)
MEDIUM_BLUE = RGBColor(0x2C, 0x5F, 0x8A)
LIGHT_GRAY = RGBColor(0x66, 0x66, 0x66)
GREEN = RGBColor(0x27, 0xAE, 0x60)
RED = RGBColor(0xE7, 0x4C, 0x3C)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)


class PresentationGenerator:
    def generate(
        self,
        ticker: str,
        company_data: dict,
        financials: dict,
        scenarios: list,
        advisory: str,
        output_path: str = None,
    ) -> str:
        """Generate a corporate finance presentation (.pptx)."""
        prs = Presentation()
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        self._add_title_slide(prs, ticker, company_data)
        self._add_company_overview(prs, company_data)
        self._add_financial_summary(prs, ticker, financials)
        self._add_scenario_analysis(prs, scenarios)
        self._add_advisory_slide(prs, advisory)
        self._add_disclaimer(prs)

        if not output_path:
            output_path = os.path.join(tempfile.gettempdir(), f"{ticker}_presentation.pptx")
        prs.save(output_path)
        return output_path

    def _add_title_slide(self, prs, ticker, data):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        # Background shape
        bg = slide.shapes.add_shape(
            1, Inches(0), Inches(0), Inches(13.333), Inches(7.5)
        )
        bg.fill.solid()
        bg.fill.fore_color.rgb = DARK_BLUE
        bg.line.fill.background()

        txBox = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(11), Inches(2))
        tf = txBox.text_frame
        p = tf.paragraphs[0]
        p.text = f"{data.get('name', ticker)} ({ticker})"
        p.font.size = Pt(40)
        p.font.bold = True
        p.font.color.rgb = WHITE
        p.alignment = PP_ALIGN.CENTER

        p2 = tf.add_paragraph()
        p2.text = "Corporate Finance Analysis"
        p2.font.size = Pt(20)
        p2.font.color.rgb = RGBColor(0xBB, 0xCC, 0xDD)
        p2.alignment = PP_ALIGN.CENTER

        p3 = tf.add_paragraph()
        p3.text = "Generated by CorpFinAI | Not Investment Advice"
        p3.font.size = Pt(12)
        p3.font.color.rgb = RGBColor(0x88, 0x99, 0xAA)
        p3.alignment = PP_ALIGN.CENTER

    def _add_company_overview(self, prs, data):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        self._add_slide_title(slide, "Company Overview")

        body = slide.shapes.add_textbox(
            Inches(0.5), Inches(1.5), Inches(12), Inches(5)
        )
        tf = body.text_frame
        tf.word_wrap = True

        mc = data.get("market_cap")
        mc_str = f"${mc / 1e9:.1f}B" if mc and mc > 0 else "N/A"

        items = [
            ("Sector", data.get("sector", "N/A")),
            ("Industry", data.get("industry", "N/A")),
            ("Market Cap", mc_str),
            ("Country", data.get("country", "N/A")),
            ("Exchange", data.get("exchange", "N/A")),
            ("Website", data.get("website", "N/A")),
        ]

        for label, value in items:
            p = tf.add_paragraph()
            run = p.add_run()
            run.text = f"{label}: "
            run.font.bold = True
            run.font.size = Pt(14)
            run.font.color.rgb = DARK_BLUE
            run2 = p.add_run()
            run2.text = str(value)
            run2.font.size = Pt(14)

        # Description
        p = tf.add_paragraph()
        p.text = ""
        p = tf.add_paragraph()
        desc = data.get("description", "No description available.")
        p.text = desc[:600] + ("..." if len(desc) > 600 else "")
        p.font.size = Pt(11)
        p.font.color.rgb = LIGHT_GRAY

    def _add_financial_summary(self, prs, ticker, ratios):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        self._add_slide_title(slide, "Financial Summary")

        sorted_periods = sorted(ratios.keys())[-4:]
        if not sorted_periods:
            body = slide.shapes.add_textbox(
                Inches(1), Inches(2), Inches(10), Inches(1)
            )
            body.text_frame.paragraphs[0].text = "No financial data available."
            return

        metrics = [
            ("Revenue ($M)", "revenue", 1e6),
            ("EBITDA ($M)", "ebitda", 1e6),
            ("Net Income ($M)", "net_income", 1e6),
            ("Gross Margin", "gross_margin", None),
            ("EBITDA Margin", "ebitda_margin", None),
            ("Revenue Growth", "revenue_growth", None),
            ("Debt/Equity", "debt_to_equity", None),
            ("FCF Margin", "fcf_margin", None),
        ]

        cols = len(sorted_periods) + 1
        rows = len(metrics) + 1
        table_shape = slide.shapes.add_table(
            rows, cols, Inches(0.5), Inches(1.5), Inches(12), Inches(4.5)
        )
        table = table_shape.table

        # Header row
        table.cell(0, 0).text = "Metric"
        for j, period in enumerate(sorted_periods):
            table.cell(0, j + 1).text = period

        # Data rows
        for i, (label, key, divisor) in enumerate(metrics):
            table.cell(i + 1, 0).text = label
            for j, period in enumerate(sorted_periods):
                val = ratios.get(period, {}).get(key)
                if val is None:
                    table.cell(i + 1, j + 1).text = "N/A"
                elif divisor:
                    table.cell(i + 1, j + 1).text = f"{val / divisor:,.0f}"
                else:
                    table.cell(i + 1, j + 1).text = f"{val:.1%}"

        # Style the table
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.text_frame.paragraphs:
                    paragraph.font.size = Pt(10)

    def _add_scenario_analysis(self, prs, scenarios):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        self._add_slide_title(slide, "Scenario Analysis: Base / Upside / Downside")

        if not scenarios:
            return

        metrics = ["Revenue Growth", "EBITDA Margin", "WACC",
                    "Terminal Growth", "DCF Value ($M)", "Implied Price"]
        cols = len(scenarios) + 1
        rows = len(metrics) + 1
        table_shape = slide.shapes.add_table(
            rows, cols, Inches(0.5), Inches(1.5), Inches(12), Inches(4)
        )
        table = table_shape.table

        table.cell(0, 0).text = "Assumption / Output"
        for j, s in enumerate(scenarios):
            a = s.get("assumptions", s) if isinstance(s, dict) else s.assumptions
            label = a.get("label", f"Scenario {j+1}") if isinstance(a, dict) else a.label
            table.cell(0, j + 1).text = label

        for j, s in enumerate(scenarios):
            a = s.get("assumptions", s) if isinstance(s, dict) else s.assumptions
            if isinstance(a, dict):
                vals = [
                    f"{a.get('revenue_growth_rate', 0):.1%}",
                    f"{a.get('ebitda_margin', 0):.1%}",
                    f"{a.get('wacc', 0):.1%}",
                    f"{a.get('terminal_growth_rate', 0):.1%}",
                    f"{s.get('dcf_value', 0) / 1e6:,.0f}",
                    f"${s.get('implied_share_price', 0):,.2f}",
                ]
            else:
                vals = [
                    f"{a.revenue_growth_rate:.1%}",
                    f"{a.ebitda_margin:.1%}",
                    f"{a.wacc:.1%}",
                    f"{a.terminal_growth_rate:.1%}",
                    f"{s.dcf_value / 1e6:,.0f}",
                    f"${s.implied_share_price:,.2f}",
                ]
            for i, v in enumerate(vals):
                table.cell(i + 1, j + 1).text = v

        for i, m in enumerate(metrics):
            table.cell(i + 1, 0).text = m

        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.text_frame.paragraphs:
                    paragraph.font.size = Pt(11)

    def _add_advisory_slide(self, prs, advisory_text):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        self._add_slide_title(slide, "Strategic Advisory")

        body = slide.shapes.add_textbox(
            Inches(0.5), Inches(1.5), Inches(12), Inches(5)
        )
        tf = body.text_frame
        tf.word_wrap = True
        
        text = advisory_text if advisory_text else "Advisory analysis not available."
        
        # Parse markdown and format properly
        lines = text.split("\n")
        for line in lines:
            stripped = line.strip()
            if not stripped:
                continue
            
            p = tf.add_paragraph()
            
            # Handle headings (remove markdown syntax)
            if stripped.startswith("#### "):
                p.text = stripped[5:]
                p.font.size = Pt(12)
                p.font.bold = True
                p.font.color.rgb = MEDIUM_BLUE
                p.space_before = Pt(8)
            elif stripped.startswith("### "):
                p.text = stripped[4:]
                p.font.size = Pt(13)
                p.font.bold = True
                p.font.color.rgb = DARK_BLUE
                p.space_before = Pt(10)
            elif stripped.startswith("## "):
                p.text = stripped[3:]
                p.font.size = Pt(14)
                p.font.bold = True
                p.font.color.rgb = DARK_BLUE
                p.space_before = Pt(12)
            elif stripped.startswith("# "):
                p.text = stripped[2:]
                p.font.size = Pt(16)
                p.font.bold = True
                p.font.color.rgb = DARK_BLUE
                p.space_before = Pt(14)
            # Handle bullet points
            elif stripped.startswith("- ") or stripped.startswith("* "):
                # Parse bold text within bullet
                content = stripped[2:]
                if "**" in content:
                    parts = content.split("**")
                    for i, part in enumerate(parts):
                        if part:
                            run = p.add_run()
                            run.text = part
                            run.font.size = Pt(10)
                            run.font.bold = (i % 2 == 1)  # Odd indices are bold
                else:
                    p.text = "• " + content
                    p.font.size = Pt(10)
                p.level = 1
            # Handle numbered lists
            elif len(stripped) > 2 and stripped[0].isdigit() and stripped[1] == ".":
                p.text = stripped
                p.font.size = Pt(11)
                p.font.bold = True
                p.font.color.rgb = MEDIUM_BLUE
                p.space_before = Pt(6)
            else:
                # Regular paragraph - handle inline bold
                if "**" in stripped:
                    parts = stripped.split("**")
                    for i, part in enumerate(parts):
                        if part:
                            run = p.add_run()
                            run.text = part
                            run.font.size = Pt(10)
                            run.font.bold = (i % 2 == 1)
                else:
                    p.text = stripped
                    p.font.size = Pt(10)

    def _add_disclaimer(self, prs):
        slide = prs.slides.add_slide(prs.slide_layouts[6])
        bg = slide.shapes.add_shape(
            1, Inches(0), Inches(0), Inches(13.333), Inches(7.5)
        )
        bg.fill.solid()
        bg.fill.fore_color.rgb = DARK_BLUE
        bg.line.fill.background()

        txBox = slide.shapes.add_textbox(
            Inches(1), Inches(2), Inches(11.333), Inches(4)
        )
        tf = txBox.text_frame
        tf.word_wrap = True
        
        p = tf.paragraphs[0]
        p.text = "DISCLAIMER"
        p.font.size = Pt(28)
        p.font.bold = True
        p.font.color.rgb = WHITE
        p.alignment = PP_ALIGN.CENTER

        p2 = tf.add_paragraph()
        p2.text = ""
        
        p3 = tf.add_paragraph()
        p3.text = (
            "This analysis was generated by CorpFinAI for educational purposes only."
        )
        p3.font.size = Pt(14)
        p3.font.color.rgb = RGBColor(0xBB, 0xCC, 0xDD)
        p3.alignment = PP_ALIGN.CENTER
        
        p4 = tf.add_paragraph()
        p4.text = (
            "It does not constitute investment advice."
        )
        p4.font.size = Pt(14)
        p4.font.color.rgb = RGBColor(0xBB, 0xCC, 0xDD)
        p4.alignment = PP_ALIGN.CENTER
        
        p5 = tf.add_paragraph()
        p5.text = (
            "All projections are estimates based on publicly available data."
        )
        p5.font.size = Pt(14)
        p5.font.color.rgb = RGBColor(0xBB, 0xCC, 0xDD)
        p5.alignment = PP_ALIGN.CENTER
        
        p6 = tf.add_paragraph()
        p6.text = "Actual results may differ materially."
        p6.font.size = Pt(14)
        p6.font.color.rgb = RGBColor(0xBB, 0xCC, 0xDD)
        p6.alignment = PP_ALIGN.CENTER

    def _add_slide_title(self, slide, title_text):
        title = slide.shapes.add_textbox(
            Inches(0.5), Inches(0.3), Inches(12), Inches(1)
        )
        p = title.text_frame.paragraphs[0]
        p.text = title_text
        p.font.size = Pt(28)
        p.font.bold = True
        p.font.color.rgb = DARK_BLUE
